### ISSUE TITLE
Frequently requests

### ISSUE THREAD

**Issue by Tockra** [mellon85/external-ip#4]
Hi,

is there some limit of the frequence of the request?

I implemented a related solution a long time ago. 
Then I requested from some web services the ip address:
https://ifconfig.me

But when I did that every 10 minutes I got response errors after some days.

T

**Comment by mellon85** [comment]
Each source might have different limits on how often if can be used, and to keep track of the usage the library would need to store state (which I wouldn't do).
DNS and IGD data sources should not have the issue.
This is also the reason why there is a consensus mechanism of the ip addresses, if you want to reduce the risk of passing request quotas for a certain service it's possible to add another resolver that won't run all sources in parallel but only one at a time

**Comment by Tockra** [comment]
Okay thank you. The IGD source is a good idea. I think I will use it in my project.

**Comment by mellon85** [comment]
With version 3 the default policy is to randomize the sources, so even if you use HTTP it should cause less problems
